dist: xenial
language: bash

before_install:
  - sudo apt update
  - sudo apt install pandoc
  - sudo apt install nodejs npm
  - npm install -g decktape

install:
  - ./build # generate slides (HTML & PDF)
  - mv .gitignore .gitignore.bak # for deployment to gh-pages

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  on:
    branch: master  

