dist: xenial
language: bash

before_install:
  - sudo apt update
  - sudo apt install pandoc
  - curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh
  - sudo bash nodesource_setup.sh
  - sudo apt-get install nodejs
  - sudo npm install --unsafe-perm -g decktape
  - sudo apt install chromium-browser
  - ldd chromium-browser | grep not

install:
  - ./build --pdf # generate slides (HTML & PDF)
  - mv .gitignore .gitignore.bak # for deployment to gh-pages

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  on:
    branch: master  

